### ISSUE TITLE
nodejs + npm

### ISSUE THREAD

**Issue by FDiskas** [eisengrind/docker-altv-server#10]
should this docker go with nodejs preinstalled?
I see .net but no npm with node

**Comment by pixlcrashr** [comment]
@FDiskas The Docker image contains only the nodejs module - **not** NPM or NodeJS itself.

If you want to use NodeJS or npm, too, on your Docker image, you can simply go ahead and extend this Docker image by creating your own Dockerfile like this:

```Dockerfile
FROM eisengrind/altv-server

RUN apt-get install <xyz>
```
