### ISSUE TITLE
FR: Add support for CDN

### ISSUE THREAD

**Issue by ekrekeler** [eisengrind/docker-altv-server#14]
Would be nice if we could use the environment variables to easily configure CDN.

Right now this would need to be done manually by installing nginx or apache in a separate container, or on top of the base image and configuring it to serve up the static content for alt:5.

See here for how this works normally: https://wiki.altv.mp/wiki/Tutorial:Setup_CDN

**Comment by pixlcrashr** [comment]
@ekrekeler Hey, thats a good point!

Will be added asap.

**Comment by pixlcrashr** [comment]
Added with commit d073c73f599e2253c5290c806eede44cfd1ca605

**Comment by pixlcrashr** [comment]
@ekrekeler Let me hear if it works, though.
You only have to wait until https://github.com/eisengrind/docker-altv-server/actions/runs/749586595
is finished.
Then, the image is also available on DockerHub.

You can set the CDN Url using the `ALTV_SERVER_CDN_URL` env var.

**Comment by pixlcrashr** [comment]
@ekrekeler Any news on this issue?

**Comment by pixlcrashr** [comment]
As there were no answers anymore, I'll close this issue.
