### ISSUE TITLE
Replacing server.cfg doesn't work

### ISSUE THREAD

**Issue by StiviiK** [eisengrind/docker-altv-server#2]
Replacing the `server.cfg` in a custom Dockerfile doesn't work. 
```
FROM eisengrind/altv-server:release-dotnet 

# Add server config
ADD build/server.cfg server.cfg
```
It will use the default one instead of my custom one.

Problem is here: https://github.com/eisengrind/docker-altv-server/blob/master/.docker/scripts/entrypoint.sh#L47
IMHO it would be better either you could specify a custom config or use your method using the env vars.

**Comment by pixlcrashr** [comment]
Thank you for the issue!

Actually, this behaviour is to be expected as the Docker image creates the server.cfg from environment variables (see `.docker/scripts/entrypoint.sh` for more info) when the container is started.

You can either configure the server.cfg using the environment variables provided in the `entrypoint.sh` script or you can overwrite the default entrypoint of the image like this:

```Dockerfile
FROM eisengrind/altv-server:release-dotnet

ADD build/server.cfg server.cfg
...

ENTRYPOINT ["<your start script or command>"]
```

---
**Off-topic:**
Btw. Keep in mind that you should use the specific tags for the altv-server as your local image will not be updated if the tag in the DockerHub registry was changed.

**Comment by StiviiK** [comment]
Then I will provide my own entrypoint.

> Btw. Keep in mind that you should use the specific tags for the altv-server as your local image will not be updated if the tag in the DockerHub registry was changed.

We are already doing this in the CI, I just use the latest tags for testing.

**Comment by pixlcrashr** [comment]
> We are already doing this in the CI, I just use the latest tags for testing.

Well then this isnt a problem at all to you.
