### ISSUE TITLE
toml config files

### ISSUE THREAD

**Issue by ZackaryH8** [eisengrind/docker-altv-server#27]
alt:V is now using TOML file format for server config files. The Docker image should reflect this.

**Comment by pixlcrashr** [comment]
gotcha, will be done asap

**Comment by pixlcrashr** [comment]
Added with 52e8bcb2e7ec2150276487d116990df7029178f8
See the [new configurator utilty](https://github.com/eisengrind/docker-altv-server/tree/master/tools/configurator) and it's CLI commands.
Wait until https://github.com/eisengrind/docker-altv-server/actions/runs/3585327795 is done

**Comment by pixlcrashr** [comment]
Btw. note that the default setting is currently to produce `.cfg` (aka `.yaml`) files because v13 is not yet released.
