### ISSUE TITLE
OS - Why choose Debian Buster-Slim and not e.g. alpine?

### ISSUE THREAD

**Issue by ThePawlow** [eisengrind/docker-altv-server#29]
Hello !

First of all I wanted to say, **thank you** so much for providing an all time up-to-date docker-image.

What's the motivation behind using debian, I personally use alpine as an base image.

Best Regards
Pavlov

**Comment by pixlcrashr** [comment]
> Hello !
> 
> First of all I wanted to say, **thank you** so much for providing an all time up-to-date docker-image.
> 
> What's the motivation behind using debian, I personally use alpine as an base image.
> 
> Best Regards Pavlov

@PavlovTM I totally get your point with alpine: It's smaller in total size (~4MB) and it is a cleaner image (less preinstalled shit :) ).
I also like alpine more for container stuff, though - and - I once tried to get the alt:V server running under alpine but sadly there were some libraries missing (and `libc` itself at the latest version; if i rember correctly.) - that would've meant that I would have to precompile the missing libraries myself within the Docker image - which isn't a problem but for which I didn't had time for at that time.
But tbh. I can give it another shot.

**Comment by ThePawlow** [comment]
Hey, wow fast reply.

No worries, I wouldn't mind creating a Pull Request for it if I should get something working.
Time is precious and it works without Alpine ! - I was just very curious.

**Comment by pixlcrashr** [comment]
> Hey, wow fast reply.
> 
> No worries, I wouldn't mind creating a Pull Request for it if I should get something working. Time is precious and it works without Alpine ! - I was just very curious.

Right. Btw. the image uses `ubuntu:focal` instead of `debian:buster-slim` - README is not correct, though. There was also an issue on `debian:buster-slim` when alt:V suddently updated it's `libc++` version.

**Comment by pixlcrashr** [comment]
@PavlovTM Before you start investing time on it:
I roughly looked over it again and the main cause is that the `altv-server` binary references `sem_clockwait` (which is an GNU glibc extension type https://www.gnu.org/software/gnulib/manual/gnulib.html#sem_005fclockwait), which however is not available under musl-like systems like alpine.
So we will not be able to run `altv-server` on alpine, except the altv publishes a binary which is compatible with musl libc or removes the failing part. It is also not said that the JS and C# modules will work properly when running against a different libc version.
It is just - highly complicated.
