### ISSUE TITLE
Wrong data type for cdnUrl env var in go-parser

### ISSUE THREAD

**Issue by datWeazel** [eisengrind/docker-altv-server#30]
In `/tools/configurator/config/server.go:70` : 
```md
CDNUrl *bool `env:"CDN_URL" toml:"cdnUrl" yaml:"cdnUrl,omitempty"`
```

Should be `*string`. Currently throws an error when using the ALTV_SERVER_CDN_URL env-var.

**Comment by pixlcrashr** [comment]
will be fixed ASAP

**Comment by datWeazel** [comment]
Sorry, my bad. Correct Type should be `url.URL` for `WEBSITE`, `CDN_URL` and `EARLY_AUTH_URL` env vars. Didn't know that the parser you use has a specific type for URL.

https://github.com/caarlos0/env

**Comment by pixlcrashr** [comment]
> Sorry, my bad. Correct Type should be `url.URL` for `WEBSITE`, `CDN_URL` and `EARLY_AUTH_URL` env vars. Didn't know that the parser you use has a specific type for URL.
> 
> https://github.com/caarlos0/env

I didn't checked it either. But we can surely add that (= less error prone configuration)

**Comment by datWeazel** [comment]
Parsing of those env vars doesn't work currently :D 

`ALTV_SERVER_CDN_URL: ${ALTV_SERVER_CDN_URL:-http://localhost:80/}`

If ALTV_SERVER_CDN_URL is unset it falls back to `http://localhost:80/` but currently the container won't start that way. 

Logs: 

```
terminate called without an active exception
/root/entrypoint.sh: line 7:    13 Aborted                 ./altv-server --config=/opt/altv/server.cfg $ALTV_SERVER_LOG_PATH $ALTV_SERVER_NO_LOGFILE ${@:1}```

**Comment by pixlcrashr** [comment]
Right, so we can not very easily use the `url.URL` type since the `toml` library does not support serializing it.
