### ISSUE TITLE
Parsing of those env vars doesn't work currently

### ISSUE THREAD

**Issue by pixlcrashr** [eisengrind/docker-altv-server#31]
> Parsing of those env vars doesn't work currently :D
> ALTV_SERVER_CDN_URL: ${ALTV_SERVER_CDN_URL:-http://localhost:80/}
> If ALTV_SERVER_CDN_URL is unset it falls back to http://localhost:80/ but currently the container won't start that way.
> Logs:

@datWeazel New Issue.

**Comment by datWeazel** [comment]
Is there any workaround for now? I really need the EarlyAuth stuff even for testing and I really don't want to setup a "traditional" Test Server. :D 

ps: If you have a ko-fi.com or PayPal.me link let me know :)

**Comment by pixlcrashr** [comment]
> Is there any workaround for now? I really need the EarlyAuth stuff even for testing and I really don't want to setup a "traditional" Test Server. :D
> 
> ps: If you have a ko-fi.com or PayPal.me link let me know :)

Should work now. Would be interesting what your results are:
***(hint: re-pull the image: `docker pull eisengrind/altv-server:release`)***
___
1.
```sh
docker run -it -e ALTV_SERVER_CDN_URL=https://example.com -e ALTV_SERVER_EARLY_AUTH_URL=https://login.example.com --entrypoint=/bin/bash eisengrind/altv-server:release
```
2. Then execute `./configurator create -o server.toml`.
3. Read the config file: `cat ./server.toml`.

**Comment by datWeazel** [comment]
Seems to be working. Thanks.
