### ISSUE TITLE
 `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by tonislcs** [eisengrind/docker-altv-server#36]
/opt/altv/configurator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/altv/configurator)
This is just using it by default i tried release and csharp-release. All i did pull the docker image and use it + assign a volume to it nothing else.

**Comment by pixlcrashr** [comment]
Thanks for your issue!

It is probably due to Debian not having the newest glibc, I assume. I'll update ASAP.

**Comment by pixlcrashr** [comment]
@realchameleon Should be fixed with the last push. Have fun. I would appreciate it if you give feedback if the new version works for you aswell.
