### ISSUE TITLE
vehmodels.bin and vehmods.bin are missing

### ISSUE THREAD

**Issue by StiviiK** [eisengrind/docker-altv-server#4]
Is there a specific reason you don't download the `vehmodels.bin` and `vehmods.bin`?

**Comment by pixlcrashr** [comment]
There is. The reason why there are no default `vehiclemodels.bin` and `vehmods.bin` is that they can be modified later on.

But I understand your problem. We could add another tag including those default data files.

**Comment by StiviiK** [comment]
I see, you got a point there. Not sure if a extra tag is required on that but at least a note in the README so people are aware of it.

**Comment by pixlcrashr** [comment]
What about using an environment variable for the image to either use default vehicle data files or custom ones?

**Comment by StiviiK** [comment]
>What about using an environment variable for the image to either use default vehicle data files or custom ones?

~But then I would recommend using the environment variable to opt-out of downloading data files.
So they are by default are included/get downloaded.~

This won't be required just download them in the Dockerfile and the User can override them using volume mounts.

**Comment by pixlcrashr** [comment]
>This won't be required just download them in the Dockerfile and the User can override them using volume mounts.

Thats a good idea.
