### ISSUE TITLE
JS Tags are broken

### ISSUE THREAD

**Issue by StiviiK** [eisengrind/docker-altv-server#7]
The new JS tags are incorrectly pushed and therefore not available.
![image](https://user-images.githubusercontent.com/8115642/84761189-5eae7400-afc9-11ea-9b2d-e3219cb7bf00.png)

**Comment by pixlcrashr** [comment]
Thanks for the issue. Will be fixed ASAP.

**Comment by pixlcrashr** [comment]
@StiviiK Should be fixed by now.

Also note that I have changed the main tag `nodejs` to `js`. (I'll provide backwards support for the `nodejs` tag).

**Comment by StiviiK** [comment]
Thanks!

**Comment by StiviiK** [comment]
@TheMysteriousVincent `libnode.so.72` is missing in the new tags.
```
docker run -it --rm eisengrind/altv-server:release-js
[14:55:05] alt:V Server, build #1181, branch release
[14:55:05] Starting Alt:V Server on Docker! on 0.0.0.0:7788
[14:55:05][Error] Failed to load "js-module.so", Unix error: libnode.so.72: cannot open shared object file: No such file or directory
[14:55:05] Starting HTTP server on 0.0.0.0:7788
[14:55:05] Server started
```

**Comment by pixlcrashr** [comment]
@StiviiK Fixed. The library could not be found due to the missing `LD_LIBRARY_PATH` variable.

**Comment by pixlcrashr** [comment]
Images are now pushed to DockerHub.

**Comment by StiviiK** [comment]
Looks good. Thanks.
